### ISSUE TITLE
Clean up logging

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/thelonious#11]
logging is handled with global variables and is a mess when the node is restarted. so:
- [x] clean up logging so things are refreshed on restart
- [ ] pipe loggers so available to rpc (and so different loggers can go different places)

**Comment by compleatang** [comment]
@ebuchman is this still required to be open? I think the logging from epm looks pretty good (and I'm pretty anal about logging). If it needs to be open is in within the 0.9 or 0.10 series?

**Comment by ebuchman** [comment]
lets kill this. we might need to reevaluate our logging strategy in the future and decouple from the ethlogger. thought it might be nice to have package level control over log level but not a priority
