### ISSUE TITLE
Stress Testing Databases

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/thelonious#18]
On thing I am worried about is our old friend Blockchain Bloat... though in this case its not Blockchain Bloat as much as it is just a large database.

Do we know how well this will function if we have terabytes worth of data stored in the chain? And that not even considering the chain itself (we possibly can mitigate chain store problems by periodically checkpointing the chain copying it to storage and modifying the genesis block to be the world state at the end of that process.)

But if the World State is terabytes worth of data we are going to have to handle it differently since we clearly won't be able to transmit it. Also I know Patricia Trees make finding data easier but do we know how it functions under extreme loads?

Should we try a simple test which deploys a bunch of contracts into a chain and then tests time to fetch a value? if we really load up the chain (I have a machine that probably could handle a 500GB worldstate.)

**Comment by compleatang** [comment]
closing this issue for now. Let's revisit this post the 0.10 sequence.
