### ISSUE TITLE
transactions as proof of work

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/thelonious#52]
So it occurred to me we should replace the idea of "amount" in a transaction with a PoW nonce. 

Then there's literally no currency.

**Comment by ebuchman** [comment]
I bring this back to 0.9 because it may be our most important anti sybil mechanism and when people ask "how do you stop sybil if no coin" at least we can point to hashcash :)

**Comment by compleatang** [comment]
roger

**Comment by ebuchman** [comment]
i simply can't tolerate development with epm anymore until binary switching is finished. implemented this in ab49dcfa743c6e1d7b72f440b7b06d56472aaad1 but can't test yet. bumping to 0.10
