### ISSUE TITLE
Discussion about secp256k1

### ISSUE THREAD

**Issue by androlo** [eris-ltd/thelonious#67]
This dependency has some (EDIT: grossly over-estimated) cross platform issues. Mainly windows and android it seems. First of all it has no build instructions for windows (and we know what that normally means...). Not sure if it's even ment to run on android. Also, only last day there was a fix to the rng. https://github.com/haltingstate/secp256k1-go/issues/5. I think it's good to make a note that this library is somewhat of a question mark, and still under development, and that we are aware of that.

Btw. apparently the Eth guys are planning on either building or finding some native go version (which I know some of you are aware of). I haven't seen any native go implementation out there. If they'll build it, that's great, but also brings about new issues. Either way, this will be with us for a while.

**Comment by haltingstate** [comment]
I think your suggestion for a full golang implementation of secp256k1 is good. I have thought more about it and you are right. I like your project and use of ipfs. Your stuff is first truely innovative thing in Bitcoin space I have seen in a while.

Please email me at HaltingState at gmail with what you are looking for.
- ex. DER encoded private keys
- signature operations
- constant time multiplication in the curve
- particular needs for your application that should be kept in mind

I have been happy with my existing library, but so many people are using it now, that it needs to be improved. I am thinking of a new library for secp256k1, poly1305-Chacha20.
