### ISSUE TITLE
Win compatibility stuff

### ISSUE THREAD

**Issue by androlo** [eris-ltd/thelonious#75]
https://github.com/eris-ltd/decerver/issues/88

so there's this, and we're gonna have to look into the auto loading of secp256k1-go, and also i think i got some key ring error. Some of the other stuff i had problems with at release could be gone with the latest merge (the one we're about to do). ill dig in again after the dapps.

**Comment by androlo** [comment]
This will be of interest I think: https://github.com/obscuren/secp256k1-go

According to obscuren, the tests has now been updated for this lib, which means we really should be able to just use it. Last i had it working on win i ran a modded haltingstate one (basically haltingstate with afew of obscurens patches + updated tests). this should make it a lot easier to verify that its safe to run on a windows machine.

**Comment by androlo** [comment]
with 'this' i mean the latest commits...

**Comment by androlo** [comment]
the secp thing was all that stopped me from actually running on win, as far as i can remember. this script_windows.go problem only had to do with old mutan stuff (remnant from eth most likely) so i just deleted it and removed the windows build directive from script.go. at least that's what i think i did (have to check the win machine). secp is probably a lot safer then i dared to assume, but since it's such an important component for safety i didn't want to green light without at least being able to run the tests.also i wanted to build 64 bit before finalizing.

**Comment by compleatang** [comment]
windows users should just use docker. let's close this for now. we can revisit if this arises as an issue for folks down the line.
