### ISSUE TITLE
Config options and Env Variables

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/thelonious#77]
To make thelonius run smoother in Docker we should allow thel to read from env variables on boot up with fail over to the current config settings. This need not be for all the settings but some of the key ones should be pulled from env vars.

**Comment by compleatang** [comment]
For reference, see here: https://registry.hub.docker.com/u/cantino/huginn/

**Comment by ebuchman** [comment]
Is this still needed?

**Comment by compleatang** [comment]
No. Its handled by the start script.
