### ISSUE TITLE
Cannot find package "bitbucket.org/kardianos/osext"

### ISSUE THREAD

**Issue by 21xhipster** [eris-ltd/thelonious#79]
`../../monk/utils.go:19:2: cannot find package "bitbucket.org/kardianos/osext" in any of:
	/usr/local/Cellar/go/1.4.1/libexec/src/bitbucket.org/kardianos/osext (from $GOROOT)
	/Users/xhipster/Github/src/bitbucket.org/kardianos/osext (from $GOPATH)
../../monkcrypto/crypto.go:7:2: cannot find package "code.google.com/p/go.crypto/ripemd160" in any of:
	/usr/local/Cellar/go/1.4.1/libexec/src/code.google.com/p/go.crypto/ripemd160 (from $GOROOT)
	/Users/xhipster/Github/src/code.google.com/p/go.crypto/ripemd160 (from $GOPATH)
../../monk/utils.go:20:2: cannot find package "github.com/eris-ltd/decerver/interfaces/dapps" in any of:
	/usr/local/Cellar/go/1.4.1/libexec/src/github.com/eris-ltd/decerver/interfaces/dapps (from $GOROOT)
	/Users/xhipster/Github/src/github.com/eris-ltd/decerver/interfaces/dapps (from $GOPATH)
../../monkdoug/blockchain.go:5:2: cannot find package "github.com/eris-ltd/eris-std-lib/go-tests" in any of:
	/usr/local/Cellar/go/1.4.1/libexec/src/github.com/eris-ltd/eris-std-lib/go-tests (from $GOROOT)
	/Users/xhipster/Github/src/github.com/eris-ltd/eris-std-lib/go-tests (from $GOPATH)
../../monk/monk.go:14:2: cannot find package "github.com/eris-ltd/modules/monkutils" in any of:
	/usr/local/Cellar/go/1.4.1/libexec/src/github.com/eris-ltd/modules/monkutils (from $GOROOT)
	/Users/xhipster/Github/src/github.com/eris-ltd/modules/monkutils (from $GOPATH)
../../../epm-go/epm/diff.go:5:2: cannot find package "github.com/eris-ltd/modules/types" in any of:
	/usr/local/Cellar/go/1.4.1/libexec/src/github.com/eris-ltd/modules/types (from $GOROOT)
	/Users/xhipster/Github/src/github.com/eris-ltd/modules/types (from $GOPATH)
`

**Comment by dennismckinnon** [comment]
looks like you need to fetch dependancies.

try `go get -d` in whatever folder you are trying to build

**Comment by 21xhipster** [comment]
Thanks
