### ISSUE TITLE
epm use wrong session key when calling "cmd transact"

### ISSUE THREAD

**Issue by ang-st** [eris-ltd/thelonious#85]
See attached pastebin 

http://pastebin.com/Qb3yZ3Xk

the key used to transact differ from the one selected in config.json ( setted by epm config key_file )

**Comment by ebuchman** [comment]
I'm about to put up a wiki to detail how this works. The problem is probably that you need to change the `key_session` too. If you just point to a new `key_file` but the `key_session` is unchanged (default is `generous` for obscure historical reasons) it will use the same key it already knew about. By changing the `key_session` though it will force it to check the key_file and copy that in to the blockchain's local dir.

**Comment by ang-st** [comment]
After some discution it appears also that model : 'std' is not supported and somewhat deprecated.
>8:09 < ei-slackbot-dev> <ebuchman> @ang-st the one thing I notice is you're using "std" as the model. you probably want "vm". "std" was a transition phase and not really supported. see  <https://github.com/eris-ltd/thelonious/blob/master/monk/defaults/genesis-advanced.json> for some boilerplate

i amended the genesis.json in this way
```
{
        "address": "0000000000THISISDOUG",
        "pdx": "",
        "doug": "Genesis DOUG/gendoug-v3.lll",
        "unique": false,
        "private-key": "",
        "model": "vm",
        "no-gendoug": false,
        "consensus": "constant",
        "difficulty": 15,
        "public:mine": 0,
        "public:create": 1,
        "public:tx": 1,
        "maxgastx": "",
        "tapow": 0,
        "blocktime": 0,
        "vm": {"suite-name":"std"},
        "accounts": [
                {
                        "address": "0x0d6bfb0bf9ff988da11236c52706cf94eef6b137",
                        "name": "theboss",
                        "balance": "1000000000000000000000000000000000000",
                        "permissions": {
                                "transact":1,
                                "mine":1,
                                "create":1,
                                "doug":1
                                },

                        "stake": 0
                }
        ]
}
```
and added `key_session`parameter along with __full__ path to the `key_file`:
`epm config key_session:mySession2 key_file:/home/vagrant/.decerver/keys/0d6bfb0bf9ff988da11236c52706cf94eef6b137`

i could then register new user thru the {{DOUG}}
```
debian-7:~$ epm keygen
bc8e932768047a54ced346e58cada7d7b5e7c508
debian-7:~$ epm  cmd transact {{DOUG}} "register alice 0xbc8e932768047a54ced346e58cada7d7b5e7c508"
2015/02/27 23:06:15 [EPM] Executing job: transact       args: [{{DOUG}} register alice 0xbc8e932768047a54ced346e58cada7d7b5e7c508]
2015/02/27 23:06:15 [EPM] Sent [0x7265676973746572 0x616c696365 0xbc8e932768047a54ced346e58cada7d7b5e7c508] to {{DOUG}}
```
i don't paste the verbose log here as it is __really__ verbose, but the executed script return 1 as expected.

**Comment by ebuchman** [comment]
:dancer:
