### ISSUE TITLE
Fix contract factories create != nodes create

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/thelonious#86]

**Comment by ebuchman** [comment]
the code seems to indicate that this is done properly: https://github.com/eris-ltd/thelonious/blob/master/monkvm/vm.go#L267

I will test it out though.

**Comment by ebuchman** [comment]
so I ran a test with public mine and public create at 0 and gave me all the permissions. deployed a contract which creates a new contract when a message is sent and then sent a message to it and it created the new contract. so from what I can tell and from what I can see in the code this is working as it should. Can you describe where this came up?

**Comment by compleatang** [comment]
It came up in exactly the context you describe. So if working now let's close the issue.
