### ISSUE TITLE
chain not found; chain instatiate calling wrong genDoug

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/thelonious#93]
i'm not sure this is the right debug, but if thel is booted to a chainID that is not found via the decerver's package.json it seems to instatiate a chain and when it does so it is trying to compile genDoug-v2... 

from slack:

```
failed compile open ~/.gvm/pkgsets/go1.4/global/src/github.com/eris-ltd/eris-std-lib/Genesis DOUG/gendoug-v2.lll: no such file or directory
2015/04/17 19:02:45 Genesis deploy failed:open ~/.gvm/pkgsets/go1.4/global/src/github.com/eris-ltd/eris-std-lib/Genesis DOUG/gendoug-v2.lll: no such file or directory
```

**Comment by ebuchman** [comment]
should it default to v3 or fail?

**Comment by dennismckinnon** [comment]
I would argue for fail. More transparent whats going wrong. Rather then make it work but in mysteriois ways.

**Comment by ebuchman** [comment]
I believe that fixes this. Can you confirm or tell me how to replicate?

**Comment by compleatang** [comment]
Bump on the reversion of this fix.... it means we aren't able to make chains on develop right now.
